### ISSUE TITLE
User Input Sanitation

### ISSUE THREAD

**Issue by dave9123** [FlashpointProject/flashpoint-database#6]
There's currently no input sanitation on the search script, please add input sanitation. Thanks!
![image](https://github.com/FlashpointProject/flashpoint-database/assets/91056752/b05cec7e-1d6a-4a38-8fd9-211bd94c6f8b)

**Comment by WumboSpasm** [comment]
It *is* sanitized, but Firefox prefers to display decoded URLs for some reason (the below image is of the raw request header). If it wasn't sanitized, you'd be able to search something like `spongebob&filter=false` and get results, but you can't.
![image](https://github.com/FlashpointProject/flashpoint-database/assets/58399748/7e8d8c48-d16f-44b7-9d60-771fe2d9504d)

Closing.
